mirrors:
  - [victorz.ca, https://victorz.ca]
  - [vwww.github.io, https://vwww.github.io]
edit_prefix: https://github.com/vwww/dev/blob/master/docs/

incremental: true

timezone: America/Edmonton

highlighter: rouge
# markdown: redcarpet
# redcarpet:
#   extensions: ['smart', 'tables', 'fenced_code_blocks', 'autolink', 'disable_indented_code_blocks', 'strikethrough', 'underline', 'highlight', 'footnotes']
permalink: /blog/:year/:month/:title
paginate: 8
paginate_path: /blog/page/:num
excerpt_separator: <!--more-->

format_date: "%A, %B %d, %Y"
format_time: "%I:%M %p %Z"
format_time_min: "%I:%M:%S %p %Z"

collections:
  code:
    output: true
    permalink: /:collection/:path
  go:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "pages"
  - scope:
      path: ""
      type: go
    values:
      layout: go-imports
  - scope:
      path: ""
      type: code
    values:
      layout: pages

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
